DROP TABLE IF EXISTS WORDS;
DROP TABLE IF EXISTS TEXT_TO_WORDS;
CREATE TABLE WORDS (
    ENT_SEQ INTEGER PRIMARY KEY NOT NULL,
    INFO TEXT NOT NULL
);
CREATE TABLE TEXT_TO_WORDS (
    TXT TEXT NOT NULL,
    ENT_SEQ INTEGER NOT NULL,
    FOREIGN KEY (ENT_SEQ) REFERENCES WORDS(ENT_SEQ)
);
